### ISSUE TITLE
Error: websock only final frames supported

### ISSUE THREAD

**Issue by hy9be** [TiddoLangerak/tracegl#4]
Sorry but I failed to find a way to fix the problem. Could you shed some lights on the potential problem and solution? Thanks!

**Comment by TiddoLangerak** [comment]
I have some bad news: this project is abandonware. I initially forked this project with the intention to clean the code up such that we could start making actual improvements and fix bugs. Unfortunately the current code-base isn't exactly the easiest to digest or maintain, and I simply don't have enough time for it. As you can see in the [commit history](https://github.com/TiddoLangerak/tracegl/commits/master), I eventually didn't do anything more than publishing the project to NPM.

So the unfortunate answer is that my guess is as good as yours, I have no idea what could cause this.

**Comment by hy9be** [comment]
Got it. Thanks though!
